version: '3'

services:
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak
        command: start
        environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KC_HOSTNAME: localhost
          KC_HOSTNAME_PORT: 8080
          KC_HOSTNAME_STRICT_BACKCHANNEL: false
          KC_HTTP_ENABLED: true
          KC_HOSTNAME_STRICT_HTTPS: false
          KC_HEALTH_ENABLED: true
        ports:
          - "8080:8080"
        restart: always
        volumes:
          - .local/keycloak/:/opt/jboss/keycloak/standalone/data/

